# Generated by Django 4.1.7 on 2023-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carshop',
            name='url',
        ),
        migrations.AddField(
            model_name='carshop',
            name='service_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carshop',
            name='service_cost',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='carshop',
            name='service_description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='carshop',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
