# Generated by Django 4.1.7 on 2023-03-29 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_remove_carshop_url_carshop_service_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rate_stars', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=100)),
                ('car_choice_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_object', to='Car.carshop')),
            ],
        ),
    ]
