# Generated by Django 4.1.7 on 2023-03-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_commentcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
