# Generated by Django 4.1.7 on 2023-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_commentpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpeople',
            name='rate_stars',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commentpeople',
            name='text',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
