# Generated by Django 4.1.7 on 2023-03-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_commentpeople_rate_stars_commentpeople_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpeople',
            name='rate_stars',
            field=models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='commentpeople',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
