# Generated by Django 4.1.7 on 2023-03-31 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0006_alter_commentpeople_rate_stars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpeople',
            name='car_choice_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_people', to='Car.carshop'),
        ),
    ]
